name: Room Watcher

on:
  schedule:
    - cron: "0 * * * *"  # כל שעה
  workflow_dispatch:

jobs:
  check_rooms:
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}  # optional
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Room Watcher
        run: python room_watcher.py
